import type { NextPage } from "next";
import Head from "next/head";
import type { PointAwardRecord } from "../lib/points";
import { useSupabase } from "../lib/hooks/supabase";
import PointsTable from "../components/PointsTable";
import testData from "../lib/data/test.json";
import SiteFooter from "../components/SiteFooter";

const HomePage: NextPage = () => {
  const session = useSupabase();

  // TODO: Replace me with database
  const records: PointAwardRecord[] = testData.map(
    ({ timestamp, ...fields }) => {
      return {
        timestamp: new Date(timestamp),
        ...fields,
      };
    }
  );

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="p-12 text-4xl font-bold text-center bg-blue-200 dark:bg-blue-800">
        Clark Point Tracker
      </header>
      <main className="min-h-[80vh] lg:mx-auto max-w-xl">
        <PointsTable records={records} />
      </main>
      <SiteFooter />
    </>
  );
};

export default HomePage;
